name: Update Systemctl Replacement Scripts

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 1 */3 *'
  push:
    paths:
      - '.github/workflows/**'

jobs:
  update-scripts-and-submodule:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: upgrade submodule to latest
        run: git submodule update --init --remote --merge

      - name: install files to repo
        run: |
          install -vDm755 src/docker-systemctl-replacement/files/docker/systemctl3.py bin/systemctl3.py
          install -vDm755 src/docker-systemctl-replacement/files/docker/journalctl3.py bin/journalctl
          install -vDm644 src/docker-systemctl-replacement/EUPL-LICENSE.md doc/EUPL-LICENSE.md
          install -vDm644 src/android-permissions/release/aids.conf local/lib/sysusers.d/aids.conf
          install -vDm644 src/android-permissions/LICENSE doc/LICENSE-Apache-2.0.txt

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(deps): update systemctl replacement scripts"
          file_pattern: '.'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
