name: Update Systemctl Replacement Scripts

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: '0 0 1 */3 *'

jobs:
  update-scripts-and-submodule:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: upgrade submodule to latest
        run: git submodule update --init --remote --merge src

      - name: install scripts to bin
        run: |
          install -vDm755 ./src/files/docker/systemctl3.py ./bin/systemctl3.py
          install -vDm755 ./src/files/docker/journalctl3.py ./bin/journalctl

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(deps): update systemctl replacement scripts"
          file_pattern: src ./bin/* .gitmodules
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com